### PR TITLE
Added support to define a background line color (Close #98)

### LINKED ISSUE #98: Define background for bookmarked lines
Just like https://github.com/alefragnani/vscode-numbered-bookmarks/issues/33

### PR DESCRIPTION
**Pull request by edgardmessias**
Not need reload for change the gutter icon or background color

### CODE REVIEW

**Comment by alefragnani** [comment]
Hi @edgardmessias ,

First of all, thanks for your PR.

Right now I'm focusing on others areas in the extension, so you will have to wait a bit prior to merge this request. Please be patience 😃

**Comment by edgardmessias** [comment]
Great. I am from Brazil. See your skype

Em qua, 1 de ago de 2018 12:55 PM, Alessandro Fragnani <
notifications@github.com> escreveu:

**Comment by alefragnani** [comment]
Hi @edgardmessias ,

Finally coming back to this 😄 

I made just one small change. I renamed the setting to `backgroundLineColor`, to stay equals to my other [Numbered Bookmarks extension](
https://github.com/alefragnani/vscode-numbered-bookmarks#available-settings). 

I hope I could release an update this weekend.

Thanks again for your PR 👍

**Comment by geekscrapy** [comment]
Can I ask where this option has been moved to? I dont see it in my settings 👀

**Comment by alefragnani** [comment]
Hi @geekscrapy ,

The `bookmarks.backgroundLineColor` setting has been deprecated a while ago. The extension now exposes `colors` which can be defined in `workbench.colorCustomizations` setting.

It's described here https://github.com/alefragnani/vscode-bookmarks#available-colors

Hope this helps

**Pull request merged**
