### PR TITLE
Multilanguage in Bookmarks. Added English and Russian language.

### PR DESCRIPTION
**Pull request by Inter-Net-Pro**
To add a new language, need to create a file package.nls.{language}.json

### CODE REVIEW

**Comment by alefragnani** [comment]
Hi @Inter-Net-Pro ,

First of all, thanks for your PR 👍 (also in Project Manager extension) .

Just like in the Project Manager extension, what about the messages that the extension displays?

**Comment by Inter-Net-Pro** [comment]
I apologize for such a pull request.
I edites a file called package.json took it from the extension in VSCode, and not from github. Only now I saw that versions differ and different indents.

**Comment by alefragnani** [comment]
There is no need to apologize. It happens 😄

**Comment by alefragnani** [comment]
Hi @Inter-Net-Pro ,

I'm finally being able to merge your PR, and I need your help for proper translation of 4 resources that has been added since you sent the PR. 

### Command

* `What's New`

### Settings

* `Background color of the decoration. Use rgba() and define transparent background colors to play well with other decorations. Ex.: rgba(21, 126, 251, 0.1)`
* `Allow navigation to wrap around at the first and last bookmarks in scope (current file or all files)`
* `Use a workaround for formatters like Prettier, which does not notify on document changes and messes Bookmark's Sticky behavior`

I thought about using Google Translator, but I'm not confident it works as expected.

Thank you

**Comment by Inter-Net-Pro** [comment]
Update came. Language was established. Super!

**Comment by alefragnani** [comment]
That’s great! 🎉 

The **Project Manager** extension should be updated next week. Stay tuned...

Thank you again

**Pull request merged**
