### PR TITLE
Added Spain Spanish translation

### PR DESCRIPTION
**Pull request by guillerpsanchez**
I have seen that the Spanish translation is not available yet, and I want to help the project with it.

I am not sure if it only need the json with the translation or it needs further changes in the code.

### CODE REVIEW

**Comment by alefragnani** [comment]
Hi @guillerpsanchez ,

First of all, thank you for the PR. 

Yes, that’s all you need to do to translate the extension, at least the “translatable” pieces 😬 . The extension also has _messages_ and other resources inside, which can’t be translated yet, but this may change in the future.

Thank you

**Comment by alefragnani** [comment]
Hi @guillerpsanchez ,

Which Language Pack are you using on your VS Code installation, in order to VS Code appear in Spanish? 

I mean, I installed the **Spanish Language Pack** from Microsoft (https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-es) and VS Code appeared Spanish, but the extension didn't. Then, I tried to change the language and noticed VS Code provides `en` and `es` (instead of `es-es`). I renamed the file to `package.nls.es.json` and it worked.

Thank you

**Comment by guillerpsanchez** [comment]
Hello,@alefragnani

I was using and old language package, as you said the `es` is the correct one, sorry for the mistake.

Have a nice day.

**Comment by alefragnani** [comment]
No problem.. it happens.

Thanks, I appreciate that 👍.  Once you update the PR I can test it again and merge, so it would be available in the next release

Thank you

**Comment by guillerpsanchez** [comment]
Hello @alefragnani ,

I have updated the PR with a new commit, it´s the first time I do it so I´m not sure if I have done it right.

Thank you and have a nice day.

**Comment by alefragnani** [comment]
Thanks @guillerpsanchez . It worked perfectly.

Stay tuned for the next release.

**Pull request merged**
