### PR TITLE
Sticky bookmarks

### PR DESCRIPTION
**Pull request by Terminux**

### CODE REVIEW

**Comment by Terminux** [comment]
This also work with the february release too

**Comment by alefragnani** [comment]
Thanks @Terminux :+1: 

Did your intention while creating `.paste`, `.moveLineUp` and `moveLineDown` commands was to _intercept the native commands_, to update the bookmarks? If yes, I think it's better to use another approach _(other than the keybindings)_, because you can't suppose that these keybindings are being used _as default_. You could end up replacing and undesired command :cry:

**Comment by Terminux** [comment]
You right. :smile: 

I have an alternative for the `moveLineUp` and `moveLineDown` commands. I work on the detection of paste (any idea ?).

**Comment by Terminux** [comment]
Hi.

I update the PR. There is no more keybindings for `moveLineUp`, `moveLineDown` and `paste` action now. :sweat_smile:

**Comment by alefragnani** [comment]
Hi @Terminux ,

Thanks for the update. I could merge it locally to execute some tests and it appears to be working fine. But I found some issues that need to be fixed, prior merging it to master.

- When you open a project previously saved, with an active file that contains any bookmarks, the `activeEditorCountLine` is not initialized (remains `undefined`), and so, the `stickyBookmarks` function doesn´t work fine. All bookmarks are moved to the first line. The reason is that `activeEditorCountLine` is updated only in the `events`, but it this case, no event is fired. You just have to update this code, right at the beginning: 

```TypeScript
    if (activeEditor) {
        if (!didLoadBookmarks) {
            bookmarks.add(activeEditor.document.uri.fsPath);
        }
        activeEditorCountLine = activeEditor.document.lineCount; // ADD THIS LINE
        activeBookmark = bookmarks.fromUri(activeEditor.document.uri.fsPath);
        triggerUpdateDecorations();
    }
```

- The bookmarks should be saved after _sticking_ bookmarks. I guess that a simple call to `saveWorkspaceState` if _some sticky is made_ is enougth. 

- If you remove lines that contains bookmarks, they are note removed, but instead, _stickied_ lines above. I also noted that if you remove the last bookmark, until the end of the file, it _stickies_ all bookmarks _n lines above_. I guess this one will be toughter :smile: 

Thanks for your help, and keep the good work :+1:

**Comment by Terminux** [comment]
Hi ! 

I update the PR with your feedback. For the last point, I can not reproduce the "remove last bookmark" case (or I don't understand :smile:). Can you explain me how have you found the error ?

**Comment by alefragnani** [comment]
Hi @Terminux 

I couldn't reproduce the _remove last bookmark_ issue anymore. Maybe I have missed something, or the error in fact does not exists :smile: . But, take a look at the GIF below, I reproduced the _remove any bookmark_, which moves the bookmark _n_ lines above. 

bookmarks-issue3-pull-request


Thanks

**Comment by Terminux** [comment]
Hello.

Thanks for the GIF. I tried to reproduce the bug without success. So strange :scream: 
I tried redoing the same deletion as you on the same file type. I tested that on mac, ubuntu, on vscode and vscode-insiders.

I will continue investigate

**Comment by alefragnani** [comment]
I was using your previous PR, so maybe the problem has been fixed with the latest. I wil update my testing branch an let you know if it's ok.

**Comment by alefragnani** [comment]
Hi @Terminux ,

I just tested your latest PR and that problem is gone :tada: 

But, I just noted that when you use code folding, the icon is drawn at the start of the folding. I added an [issue](https://github.com/Microsoft/vscode/issues/4812) in vscode repo, and they already marked as _bug_, so it's just a matter of time for the fix. I guess it will be fixed soon :smile: 

Thanks again for your support.

**Comment by alefragnani** [comment]
Hi @Terminux ,

Since the _folding_ issue reported above also happens with _breakpoints_, I think we don't need to hold your PR for that to be solved:+1: 

But, when I was doing the merge, I found some issues when making changes in the text _near and at_ the bookmarked lines. Unfortunately I can't look at it right now, so if you could take a look, I appreciate.

1. Enter in bookmarked lines
bookmarks-enter-in-bookmarked-line


1. Delete above bookmarked lines
bookmarks-delete-above-bookmarked-line


1. Backspace at bookmarked lines
bookmarks-backspace-at-bookmarked-line

Thanks for your help

**Comment by alefragnani** [comment]
Stay tunned... will be released tomorrow :+1:

**Comment by Terminux** [comment]
Hello @alefragnani 

Sorry I returned from vacation yesterday. You want me to watch your feedback or you managed to fix ?

**Comment by alefragnani** [comment]
Don't worry.. Vacations are meant to relax :smile: 
Yes, I managed to fix. I wanted to release yesterday but had some other stuff to do (not related to this), but until Saturday it will be released.

Thanks, and congrats for your efforts :+1: .

**Pull request merged**
